#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.296
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ERPProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="TestDevExpress")]
	public partial class ERPDataDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    #endregion
		
		public ERPDataDataContext() : 
				base(global::ERPProject.Properties.Settings.Default.TestDevExpressConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public ERPDataDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPDataDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPDataDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public ERPDataDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Module> Module
		{
			get
			{
				return this.GetTable<Module>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Module")]
	public partial class Module
	{
		
		private long _Indx;
		
		private string _SystemID;
		
		private string _MpCode;
		
		private string _MpName;
		
		private string _MpParentCode;
		
		private bool _IsOPeration;
		
		private string _Remark;
		
		private string _Url;
		
		public Module()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Indx", AutoSync=AutoSync.Always, DbType="BigInt NOT NULL IDENTITY", IsDbGenerated=true)]
		public long Indx
		{
			get
			{
				return this._Indx;
			}
			set
			{
				if ((this._Indx != value))
				{
					this._Indx = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SystemID", DbType="Char(10) NOT NULL", CanBeNull=false)]
		public string SystemID
		{
			get
			{
				return this._SystemID;
			}
			set
			{
				if ((this._SystemID != value))
				{
					this._SystemID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MpCode", DbType="Char(18) NOT NULL", CanBeNull=false)]
		public string MpCode
		{
			get
			{
				return this._MpCode;
			}
			set
			{
				if ((this._MpCode != value))
				{
					this._MpCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MpName", DbType="NChar(20) NOT NULL", CanBeNull=false)]
		public string MpName
		{
			get
			{
				return this._MpName;
			}
			set
			{
				if ((this._MpName != value))
				{
					this._MpName = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MpParentCode", DbType="Char(18) NOT NULL", CanBeNull=false)]
		public string MpParentCode
		{
			get
			{
				return this._MpParentCode;
			}
			set
			{
				if ((this._MpParentCode != value))
				{
					this._MpParentCode = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsOPeration", DbType="Bit NOT NULL")]
		public bool IsOPeration
		{
			get
			{
				return this._IsOPeration;
			}
			set
			{
				if ((this._IsOPeration != value))
				{
					this._IsOPeration = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Remark", DbType="NVarChar(200)")]
		public string Remark
		{
			get
			{
				return this._Remark;
			}
			set
			{
				if ((this._Remark != value))
				{
					this._Remark = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Url", DbType="NVarChar(20)")]
		public string Url
		{
			get
			{
				return this._Url;
			}
			set
			{
				if ((this._Url != value))
				{
					this._Url = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
